# Set the parent image
FROM node:gallium-bullseye

# Set the working directory
WORKDIR /usr/src/smart-brain-api

# Copy everything on the root directory (the same in which the dockerfile is)
#to a relative path (from the workdir)
COPY . .

# Commands to run during the image building (image building steps)
RUN npm install
RUN apt update # Needed to download the packages list
RUN apt install -y vim 

# Executes by default when launching the built image (has to be unique)
CMD ["/bin/bash"]
